"""HTML and Markdown presentation report templates for SatQuery AI Division 5."""

from __future__ import annotations

HTML_REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SatQuery AI Analysis Report — {request_id}</title>
  <style>
    :root {{
      --bg-primary: #0a0e17;
      --bg-card: #121826;
      --bg-surface: #1a2234;
      --accent-blue: #3b82f6;
      --accent-cyan: #06b6d4;
      --accent-emerald: #10b981;
      --accent-amber: #f59e0b;
      --accent-red: #ef4444;
      --text-main: #f3f4f6;
      --text-muted: #9ca3af;
      --border-subtle: rgba(255, 255, 255, 0.08);
    }}
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      background-color: var(--bg-primary);
      color: var(--text-main);
      line-height: 1.6;
      padding: 32px 16px;
    }}
    .report-container {{
      max-width: 1000px;
      margin: 0 auto;
      background: var(--bg-card);
      border: 1px solid var(--border-subtle);
      border-radius: 12px;
      padding: 32px;
      box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4);
    }}
    .report-header {{
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      border-bottom: 1px solid var(--border-subtle);
      padding-bottom: 20px;
      margin-bottom: 24px;
    }}
    .brand-title {{
      font-size: 24px;
      font-weight: 800;
      color: var(--accent-cyan);
      display: flex;
      align-items: center;
      gap: 10px;
    }}
    .meta-tag {{
      font-size: 12px;
      color: var(--text-muted);
      margin-top: 4px;
    }}
    .section {{
      margin-bottom: 28px;
    }}
    .section-title {{
      font-size: 15px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--accent-cyan);
      margin-bottom: 12px;
      display: flex;
      align-items: center;
      gap: 8px;
    }}
    .query-box {{
      background: var(--bg-surface);
      border-left: 4px solid var(--accent-blue);
      padding: 16px;
      border-radius: 4px;
      font-size: 16px;
      margin-bottom: 16px;
    }}
    .answer-box {{
      background: rgba(16, 185, 129, 0.06);
      border: 1px solid rgba(16, 185, 129, 0.25);
      border-radius: 8px;
      padding: 20px;
      font-size: 16px;
      color: #e5e7eb;
    }}
    .grid-2 {{
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 16px;
    }}
    @media (max-width: 768px) {{
      .grid-2 {{ grid-template-columns: 1fr; }}
    }}
    .info-card {{
      background: var(--bg-surface);
      border: 1px solid var(--border-subtle);
      border-radius: 8px;
      padding: 16px;
    }}
    .info-row {{
      display: flex;
      justify-content: space-between;
      font-size: 13px;
      padding: 6px 0;
      border-bottom: 1px solid rgba(255, 255, 255, 0.04);
    }}
    .info-label {{ color: var(--text-muted); }}
    .info-value {{ font-weight: 600; color: var(--text-main); }}
    .evidence-gallery {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
      gap: 16px;
      margin-top: 12px;
    }}
    .evidence-card {{
      background: var(--bg-surface);
      border: 1px solid var(--border-subtle);
      border-radius: 8px;
      overflow: hidden;
    }}
    .evidence-img {{
      width: 100%;
      height: 220px;
      object-fit: cover;
      display: block;
      background: #000;
    }}
    .evidence-desc {{
      padding: 12px;
      font-size: 12px;
    }}
    .limitations-box {{
      background: rgba(245, 158, 11, 0.06);
      border: 1px solid rgba(245, 158, 11, 0.25);
      border-radius: 8px;
      padding: 16px;
      font-size: 13px;
      color: #fde68a;
    }}
    .print-btn {{
      background: var(--accent-blue);
      color: white;
      border: none;
      padding: 8px 16px;
      border-radius: 6px;
      font-weight: 600;
      cursor: pointer;
    }}
    @media print {{
      body {{ background: white; color: black; }}
      .report-container {{ border: none; box-shadow: none; padding: 0; }}
      .print-btn {{ display: none; }}
    }}
  </style>
</head>
<body>
  <div class="report-container">
    <div class="report-header">
      <div>
        <div class="brand-title">🛰️ SatQuery AI — Intelligence Report</div>
        <div class="meta-tag">Generated by Division 5 (Evidence & Presentation Layer)</div>
        <div class="meta-tag">Request ID: <code>{request_id}</code> | Timestamp: {timestamp}</div>
      </div>
      <button class="print-btn" onclick="window.print()">🖨️ Print / Save PDF</button>
    </div>

    <!-- Section 1: Query & Response -->
    <div class="section">
      <div class="section-title">💬 Natural Language Query & Answer</div>
      <div class="query-box">
        <strong>Query:</strong> "{query}"
      </div>
      <div class="answer-box">
        <div style="display: flex; justify-content: space-between; margin-bottom: 8px;">
          <strong>Synthesized Specialist Answer:</strong>
          {confidence_badge_html}
        </div>
        <div>{answer}</div>
      </div>
    </div>

    <!-- Section 2: Input & Context Summary -->
    <div class="section">
      <div class="section-title">🛰️ Ingested Remote-Sensing Imagery</div>
      <div class="grid-2">
        <div class="info-card">
          <div class="info-row"><span class="info-label">Resolved Task:</span><span class="info-value">{resolved_task}</span></div>
          <div class="info-row"><span class="info-label">Input Count:</span><span class="info-value">{image_count} raster(s)</span></div>
          <div class="info-row"><span class="info-label">Observed Modalities:</span><span class="info-value">{modalities}</span></div>
        </div>
        <div class="info-card">
          <div class="info-row"><span class="info-label">Selected Specialist Tool:</span><span class="info-value">{selected_tools}</span></div>
          <div class="info-row"><span class="info-label">Execution Status:</span><span class="info-value">{status}</span></div>
          <div class="info-row"><span class="info-label">Total Processing Latency:</span><span class="info-value">{total_latency}</span></div>
        </div>
      </div>
    </div>

    <!-- Section 3: Grounding Visual Evidence -->
    <div class="section">
      <div class="section-title">🔍 Visual Grounding Evidence & Spatial Artifacts</div>
      <div class="evidence-gallery">
        {evidence_cards_html}
      </div>
    </div>

    <!-- Section 4: Auditable Execution Trace -->
    <div class="section">
      <div class="section-title">⏱️ Auditable Execution Trace</div>
      {trace_timeline_html}
    </div>

    <!-- Section 5: System Limitations & Disclaimers -->
    <div class="section">
      <div class="section-title">⚠️ Limitations & Disclaimers</div>
      <div class="limitations-box">
        <p><strong>Operational Boundary Notice:</strong></p>
        <ul style="padding-left: 20px; margin-top: 6px;">
          {limitations_list_html}
        </ul>
      </div>
    </div>
  </div>
</body>
</html>
"""
