"""Core package for SatQuery AI containing canonical contracts, interfaces, errors, and config."""

from core.config import settings
from core.errors import (
    ConfigurationError,
    ErrorCode,
    IncompatiblePairError,
    InferenceError,
    InputValidationError,
    InvalidImageCountError,
    MissingMetadataError,
    ModelLoadError,
    OutputValidationError,
    SatQueryException,
    TaskNotSupportedError,
    ToolNotFoundError,
    ToolTimeoutError,
    UnsupportedFormatError,
    UnsupportedModalityError,
)
from core.interfaces import BaseSpecialistTool, ValidationResult
from core.logging import get_logger, set_request_id, setup_logging
from core.schemas import (
    Artifact,
    Evidence,
    EvidenceType,
    ExecutionStage,
    ExecutionTraceEntry,
    GeoSpatialMetadata,
    ImageFormat,
    ImageInput,
    ImageModality,
    ImagePairType,
    QueryRequest,
    QueryResponse,
    SatQueryErrorDetail,
    TaskIntent,
    TaskType,
    ToolMetadata,
    ToolRequest,
    ToolResult,
    ToolStatus,
)

__all__ = [
    "settings",
    "ErrorCode",
    "SatQueryException",
    "InputValidationError",
    "UnsupportedFormatError",
    "UnsupportedModalityError",
    "InvalidImageCountError",
    "IncompatiblePairError",
    "MissingMetadataError",
    "TaskNotSupportedError",
    "ToolNotFoundError",
    "ModelLoadError",
    "InferenceError",
    "ToolTimeoutError",
    "OutputValidationError",
    "ConfigurationError",
    "BaseSpecialistTool",
    "ValidationResult",
    "get_logger",
    "set_request_id",
    "setup_logging",
    "ImageModality",
    "ImageFormat",
    "ImagePairType",
    "TaskType",
    "EvidenceType",
    "ToolStatus",
    "ExecutionStage",
    "GeoSpatialMetadata",
    "ImageInput",
    "TaskIntent",
    "Evidence",
    "Artifact",
    "ExecutionTraceEntry",
    "ToolRequest",
    "ToolResult",
    "ToolMetadata",
    "SatQueryErrorDetail",
    "QueryRequest",
    "QueryResponse",
]
